### ISSUE TITLE
Can't change big files due to Happstack's BodyPolicy

### ISSUE THREAD

**Issue by fkohrt** [jgm/gitit#638]
Saving a change for a file with a size of 81.5 KB leads to the following error message: `x-www-form-urlencoded content longer than BodyPolicy.maxRAM=100000 bytes`.

I am using a fresh [experimental docker version](https://hub.docker.com/r/t13a/gitit-experimental) ([repo](https://github.com/t13a/dockerfile-gitit-experimental)) of gitit by [t13a](https://github.com/t13a).

Any ideas what I could do? Changing the `max-page-size` inside the `gitit.conf` does not help.

**Comment by jgm** [comment]
I've never heard of this (and never ran into it myself).  If you track down what's going in in Happstack, maybe we can fix it, but I don't have bandwidth to look into it myself now.

**Comment by adamdaugherty** [comment]
@fkohrt I realize this was a long time ago, but just in case you're still dealing with it or someone else that is happens across this issue, I recently encountered a similar one and might have a way to address it.

After changing my `gitit.conf` to set `max-upload-size` to `0K` and trying to log in, I was informed that it had failed due to`x-www-form-urlencoded content longer than BodyPolicy.maxRAM=0 bytes`. Thankfully, that was the only relevant change that I'd made recently to the configuration, so it was easy to track down.

Accordingly, it might be worthwhile to try messing with `max-upload-size` to see if it gets you past the issue. It's counterintuitive because I would think of an "upload" to mean a file, but I guess that technically a change to a page (or in my case, sending my credentials) could be considered an upload if you stare at it from the right angle, so it kinda makes sense that that option might apply in addition to `max-page-size`.

**Comment by fkohrt** [comment]
@adamdaugherty Shame on me that I didn't try `max-upload-size`. Yes indeed, that helped; thank you kindly!
